name: Build and Deploy Next.js App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    # This makes GitHub use YOUR EC2 runner instead of GitHub's servers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          # This runs ON YOUR EC2 runner!
          docker build -t my-nextjs-app:${{ github.sha }} .
          docker tag my-nextjs-app:${{ github.sha }} my-nextjs-app:latest

      - name: Save Docker image
        run: |
          # Save image as a file to transfer it
          docker save my-nextjs-app:latest | gzip > nextjs-app.tar.gz

      - name: Deploy to Production VM
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
          # Copy Docker image to production
          scp -i ~/.ssh/deploy_key nextjs-app.tar.gz $DEPLOY_USER@$DEPLOY_HOST:/home/$DEPLOY_USER/

          # Deploy on production server
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            # Load Docker image
            docker load < /home/deploy/nextjs-app.tar.gz

            # Stop and remove old container if exists
            docker stop nextjs-app || true
            docker rm nextjs-app || true

            # Run new container
            docker run -d \
              --name nextjs-app \
              --restart unless-stopped \
              -p 3000:3000 \
              my-nextjs-app:latest

            # Clean up
            rm /home/deploy/nextjs-app.tar.gz

            # Remove old images (optional)
            docker image prune -f
          EOF

          # Clean up local SSH key
          rm ~/.ssh/deploy_key
