name: Build and Deploy Next.js App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # ✅ Use GitHub runner (not self-hosted)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-nextjs-app:${{ github.sha }} .
          docker tag my-nextjs-app:${{ github.sha }} my-nextjs-app:latest

      - name: Save Docker image
        run: |
          docker save my-nextjs-app:latest | gzip > nextjs-app.tar.gz

      - name: Deploy to Production VM
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}   # Your EC2 Elastic IP
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}   # e.g., deploy
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}     # Private key
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${DEPLOY_KEY}" > ~/.ssh/deploy_key   # ✅ Wrapped in quotes
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

          # Copy Docker image to production
          scp -i ~/.ssh/deploy_key nextjs-app.tar.gz $DEPLOY_
