name: Build and Deploy Next.js App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    # Use GitHub-hosted runner instead of self-hosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-nextjs-app:${{ github.sha }} .
          docker tag my-nextjs-app:${{ github.sha }} my-nextjs-app:latest

      - name: Save Docker image
        run: |
          docker save my-nextjs-app:latest | gzip > nextjs-app.tar.gz

      - name: Deploy to Production VM
        env:
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}      # EC2 Elastic IP
          DEPLOY
